################################################################################
# ML.NET's PR validation build
################################################################################

resources:
  containers:
  - container: CentosContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-8bba86b-20190314145033
  
  - container: UbuntuContainer
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-mlnet-207e097-20190312152303

jobs:
- template: /build/ci/job-template.yml
  parameters:
    name: MacOS_x64_NetCoreApp21
    buildScript: ./build.sh
    pool:
      name: Hosted macOS High Sierra